theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"

[[block]]
block = "disk_space"

[[block]]
block = "maildir"
inboxes = ["/home/pmc/Maildir/fastmail/Inbox"]

[[block]]
block = "memory"

[[block]]
block = "music"
player = "mpd"

[[block]]
block = "sound"

[[block]]
block = "time"
